version: "3.9"
services:
  ftec-project:
      build:
        dockerfile: ./Dockerfile
      container_name: ftec-project
      ports:
      - "8888:8888"
      env_file:
        - .env.compose
      depends_on:
        - postgres
      networks:
        app-network:
          aliases:
            - "ftec-project.private"

  postgres:
    image: postgres:12.3-alpine
    container_name: postgres-sample
    hostname: postgres
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sample
    networks:
      app-network:
        aliases:
          - "postgres.private"

networks:
  app-network:

